version: '3'

services:

  peoplecounter_in_api:
    build: ./platform_in/
    entrypoint: ['/project/entrypoint.sh']
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./platform_in/:/project/
    ports:
      - 5002:5000
    env_file:
      - var.env
    #  - dev.env
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig  

    
